language: julia
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      before_install:
        - sudo apt-get -y install pandoc
        - pip install --user nbconvert
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success:
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
