language: julia
julia: 1.4
os: linux
jobs:
  include:
    - stage: "Unit test"
      os:
        - linux
        - osx
        - windows
      script:
        - julia --project=test/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=test/ --code-coverage test/runtests.jl
        - julia --project=test/ test/performance.jl
      after_success:
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
    - stage: "Documentation"
      before_install:
        - sudo apt-get -y install pandoc
        - pip install --user nbconvert
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
