language: julia
julia: 1.2
os: linux
jobs:
  include:
    - stage: "Unit test"
      script:
        - julia --code-coverage test/runtests.jl
        - julia test/performance.jl
      after_success:
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
    - stage: "Documentation"
      before_install:
        - sudo apt-get -y install pandoc
        - pip install --user nbconvert
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
