name = "FunctionOperators"
uuid = "98ce4118-165c-488a-9b71-2bb5aff4e594"
authors = ["HAKKEL Tamás <hakkel.tamas@ppke.hu>"]
version = "0.1.0"

[compat]
julia = "1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
